# Generated by Django 4.2.6 on 2023-10-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('FAMILY', 'Family Room'), ('DELUXE', 'Deluxe Room'), ('SUITE', 'Suite')], max_length=6),
        ),
    ]
