# Generated by Django 4.2.6 on 2023-10-30 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_alter_confirmation_confirmed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
