# Generated by Django 4.2.7 on 2023-12-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_employeeschedule_work_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='client_bookings', to='hotel.bookings'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='hotel.client'),
        ),
    ]
